package com.ftcoding.habitandscheduletracker.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFFa8327b)


val seed = Color(0xFF1E6262)
val Color3 = Color(0xFF333333)


val md_theme_light_primary = Color(0xFF006A6A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6FF7F6)
val md_theme_light_onPrimaryContainer = Color(0xFF002020)
val md_theme_light_secondary = Color(0xFF006972)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF8FF2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001F23)
val md_theme_light_tertiary = Color(0xFF00696A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF6FF6F8)
val md_theme_light_onTertiaryContainer = Color(0xFF002020)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF2FFFD)
val md_theme_light_onBackground = Color(0xFF00201E)
val md_theme_light_surface = Color(0xFFF2FFFD)
val md_theme_light_onSurface = Color(0xFF00201E)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E4)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
val md_theme_light_outline = Color(0xFF6F7979)
val md_theme_light_inverseOnSurface = Color(0xFFB1FFF8)
val md_theme_light_inverseSurface = Color(0xFF003734)
val md_theme_light_inversePrimary = Color(0xFF4CDADA)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006A6A)
val md_theme_light_outlineVariant = Color(0xFFBEC9C8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4CDADA)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF004F50)
val md_theme_dark_onPrimaryContainer = Color(0xFF6FF7F6)
val md_theme_dark_secondary = Color(0xFF4ED8E9)
val md_theme_dark_onSecondary = Color(0xFF00363C)
val md_theme_dark_secondaryContainer = Color(0xFF004F56)
val md_theme_dark_onSecondaryContainer = Color(0xFF8FF2FF)
val md_theme_dark_tertiary = Color(0xFF4CDADB)
val md_theme_dark_onTertiary = Color(0xFF003737)
val md_theme_dark_tertiaryContainer = Color(0xFF004F50)
val md_theme_dark_onTertiaryContainer = Color(0xFF6FF6F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00201E)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF00201E)
val md_theme_dark_onSurface = Color(0xFF70F7EE)
val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C8)
val md_theme_dark_outline = Color(0xFF889392)
val md_theme_dark_inverseOnSurface = Color(0xFF00201E)
val md_theme_dark_inverseSurface = Color(0xFF70F7EE)
val md_theme_dark_inversePrimary = Color(0xFF006A6A)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4CDADA)
val md_theme_dark_outlineVariant = Color(0xFF3F4948)
val md_theme_dark_scrim = Color(0xFF000000)

